/*
 * Roll Image
 *
 * Version 1.0 2012/11/19 Crytus corporation
 */
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('7 h=0;7 9="";7 i;7 s;7 t=\'\';7 8;7 p=0;7 c;7 u;7 C=6;7 V=4;d v(){3(p){9="5";3(f.j&&b(8.a.5)>(i-t)){8.a.5=b(8.a.5)-h+"w"}k{9="q";l=m("x();",y);H}}n=m("v();",D)}d x(){3(p){9="q";3(f.j&&b(8.a.5)<0){8.a.5=b(8.a.5)+h+"w"}k{9="5";n=m("v();",y);H}}l=m("x();",D)}d I(e){3(c){J(c);c=z}7 A=o.K?K.E:e.E?e.E:"";A-=s-((o.L)?L:f.W.X);7 M=(i-C)/2;7 N=(i+C)/2;3(A>N){h=1;3(o.l)B(l);3(9!="5")v()}k 3(A<M){h=1;3(o.n)B(n);3(9!="q")x()}k{h=0}}d F(O){u=z;9=O}d P(G){3(p){3(f.j){3(9=="5"){3(b(8.a.5)>(i-t)){8.a.5=b(8.a.5)-G+"w"}k{9="";u=m("F(\'q\');",y)}}3(9=="q"){3(b(8.a.5)<0){8.a.5=b(8.a.5)+G+"w"}k{9="";u=m("F(\'5\');",y)}}}}}d Y(Q,R){3(f.j){7 g=f.j(Q);3(g){i=b(g.a.S);s=g.T;7 r=g.U;Z(r!=z){s+=r.T;r=r.U}8=f.j(R);t=b(8.a.S);g.10=d(e){3(o.n)B(n);3(o.l)B(l);9="";3(c){J(c);c=z}};g.11=d(e){I(e)};p=1;9="5";c=12("P(1);",D)}}}',62,65,'|||if||left||var|roll_content|roll_movestate|style|parseInt|roll_timer_init|function||document|roll_body|roll_speed|roll_width|getElementById|else|righttime|setTimeout|lefttime|window|roll_ready|right|parentEl|roll_offset|roll_content_width|roll_time|roll_moveleft|px|roll_moveright|1000|null|curposx|clearTimeout|roll_stop|30|clientX|roll_change|speed|return|roll_motion|clearInterval|event|pageXOffset|leftbound|rightbound|dir|roll_initial|window_id|roll_image|width|offsetLeft|offsetParent|roll_max|body|scrollLeft|roll_images|while|onmousemove|onmouseout|setInterval'.split('|'),0,{}));

// 表示窓と表示内容のIDを指定して開始
roll_images("roll_window", "roll_contents");
